### ISSUE TITLE
Triggering Travis Buddy on failure only, without changing other webhooks

### ISSUE THREAD

**Issue by ehmicky** [bluzi/travis-buddy#136]
Hi there, thanks for this great project!

I would like Travis buddy to create comments only when the Travis build is failing. The `README` suggests using `on_success: never`. However this does not work if there are other webhooks, as it will set `on_success` for them as well, which might not be desired.

For example my `.travis.yml` looks like:

```yml
notifications:
  webhooks:
    - https://coveralls.io/webhook
    - https://www.travisbuddy.com
  # I cannot uncomment this, as this would make Coveralls webhook not work anymore
  # on_success: never
```
