### ISSUE TITLE
Add travisBuddy node in .travis.yml

### ISSUE THREAD

**Issue by bluzi** [bluzi/travis-buddy#73]
## Summary
@TravisBuddy should be able to pull configurations from a node `travisBuddy` in `.travis.yml`.
Example structure:
```yml
language: node_js
node_js:
  - '8'
notifications:
  webhooks:
    urls:
      - 'https://www.travisbuddy.com/'
travisBuddy: 
  templates:
    success: default
    failure: default
  insertMode: update
```

There should be no required fields (even `travisBuddy` isn't required)

## How to resolve?
Add `configuration.js` to `utils/`, and make it a module that loads the configuration from the `.travis.yml` of a repository and query it.

In `routes/api.routes.js`, use `utils/configuration.js` to load the configuration from the requested repository (the repository name is available via `data.owner` and `data.repo`)

From there, every module should be able to query configuration by importing `configuration.js` and calling a `query` function.
